# https://github.com/eksctl-io/eksctl/tree/main/examples
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spread
  region: eu-west-1
  version: 1.28
  tags:
    repo: github.com/the-technat/topologySpreadConstraints
kubernetesNetworkConfig:
  ipFamily: IPv4
  serviceIPv4CIDR: 10.127.0.0/16
vpc:
  cidr: 10.123.0.0/16
  nat:
    gateway: single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
iam:
  withOIDC: true
accessConfig:
  authenticationMode: API
  bootstrapClusterCreatorAdminPermissions: true
managedNodeGroups:
  - name: a
    availabilityZones: ["eu-west-1a"]
    spot: true
    instanceType: t3a.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      enableSsm: true
  - name: b
    availabilityZones: ["eu-west-1b"]
    spot: true
    instanceType: t3a.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      enableSsm: true
  - name: c
    availabilityZones: ["eu-west-1c"]
    spot: true
    instanceType: t3a.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      enableSsm: true
