rollOutCiliumPods: true
cluster:
  name: ${cluster_name}
hubble:
  enabled: true
  relay:
    rollOutPods: true
    enabled: true
routingMode: "native"
eni:
  enabled: true
ipam:
  mode: eni
  awsEnablePrefixDelegation: true
kubeProxyReplacement: strict
k8sServicePort: 443
k8sServiceHost: ${cluster_endpoint}
operator:
  rollOutPods: true
  replicas: 1
